name: compile-and-test-C-program

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: hello.exe
          path: hello.exe
      
      - name: Install gcc
        run: "sudo apt-get install -y gcc"
        
      - name: Compile code
        run: "gcc hello.c -o hello.exe"

      - name: Run tests
        run: |
          if ./hello.exe; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
