name: compile-and-test-C-program

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang]
        artifact-name: [gcc_hello.exe, clang_hello.exe]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install ${{ matrix.compiler }}
        run: "sudo apt-get install -y ${{ matrix.compiler }}"
        
      - name: Compile code
        run: "${{ matrix.compiler }} hello.c -o ${{ matrix.artifact-name }}"

      - name: Run tests
        run: |
          if ./${{ matrix.artifact-name }}; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-name }}
