name: learn-github-actions  # name of the workflow

run-name: ${{ github.actor }} is learning GitHub Actions # name of individual runs of the workflow

on: 
  - push

jobs: {check-bats-version: {runs-on: ubuntu-latest, steps: [uses: actions/checkout@v5, {uses: actions/setup-node@v4, with: [node-version: '20']}, run: npm install -g bats, run: bats -v ]}}
