name: vulnerable-secret

on: 
  workflow_dispatch:
    inputs:
      code:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.password }}
    steps:
      - name: echo code
        run: |
          echo ${{ inputs.code }}
      